#!/bin/bash
TOKEN="533091221:AAB0gTvmqQMT--ejYsTU"
POST=0
LASTPOSTLINK=$(cat ~/.monkeyuserlastpost)
for LINK in $(curl -L http://www.monkeyuser.com/feed.xml | xml_grep --text_only link | head -6 | tac | head -5)
do
        if [ "$POST" = "0" ]
        then
                if [ "$LASTPOSTLINK" = "$LINK" ]
                then
                        POST=1
                fi
        else
                curl -L "$LINK" > ~/.monkeytemp
                IMGURL="$(cat ~/.monkeytemp | egrep -A 4 'class="content"' | grep -P -o https:\/\/www\.monkeyuser\.com\/assets\/images.+?\" | sed -r 's/.{1}$//' | tail -1)"
                wget "$IMGURL" -O /root/.file.png
                TITLE="$(cat ~/.monkeytemp | xml_grep --html --text_only title)"
                ENCODED_TITLE="$(urlencode $TITLE)"
                ENCODED_URL="$(urlencode $LINK)"
                curl "https://api.telegram.org/bot$TOKEN/sendPhoto?chat_id=@monkeyusers&caption=$ENCODED_TITLE%0A$ENCODED_URL%0A@monkeyusers" -F photo=@/root/.file.png
                rm /root/.file.png
                echo "$LINK" > ~/.monkeyuserlastpost
        fi
done
rm ~/.monkeytemp
