#!/bin/bash

#apt install curl xml-twig-tools gridsite-clients w3m

while true;
do

BOT_TOKEN="$TOKEN"
WORKING_DIR="/files"
POST=0
LASTPOSTLINK="$(cat $WORKING_DIR/tcllastpostlink)"

for LINK in $(curl -k https://thecodinglove.com/feed > file.txt && xml_grep item file.txt > file1.txt && xml_grep link --text_only file1.txt | tac)
#for LINK in $(cat $WORKING_DIR/tcltemplink | tac)
do
    if [ "$POST" = "0" ]
    then
        echo "link:      $LINK"
        echo "last link: $LASTPOSTLINK"
        if [ "$LASTPOSTLINK" = "$LINK" ]
        then
            POST=1
            echo found
        fi
    else
        echo "LINK: $LINK"
        curl -k $LINK > "$WORKING_DIR/tcltemp"
        TITLE="$(cat $WORKING_DIR/tcltemp | grep 'property="og:title"' | sed -r 's/^.{36}//' | sed -r 's/.{61}$//' | w3m -dump -T text/html)"
        echo "TITLE: $TITLE"
        ENCODED_TITLE="$(urlencode $TITLE)"
        echo "ENCODED_TITLE: $ENCODED_TITLE"
        IMGLINK="$(cat $WORKING_DIR/tcltemp | grep -A 6 blog-post-content | tr ">" "\n" | grep -E 'img|image' | sed -r 's/^.{14}//' | sed -r 's/.{18}$//')"
        FILENAME="$(basename $IMGLINK)"
        curl -k -o "$WORKING_DIR/$FILENAME" "$IMGLINK"
        echo "IMGLINK: $IMGLINK"
        ENCODED_IMGLINK="$(urlencode $IMGLINK)"
        curl "https://api.telegram.org/bot$BOT_TOKEN/sendDocument?chat_id=@tclunofficial&caption=$ENCODED_TITLE%0A@tclunofficial" -F document=@"$WORKING_DIR/$FILENAME"
        rm "$WORKING_DIR/$FILENAME"
        echo "$LINK" > "$WORKING_DIR/tcllastpostlink"
    fi
done

sleep 600

done
